version: '2'
services:
    quanda-app:
        image: quanda
        external_links:
            - quanda-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/quanda?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    quanda-mysql:
        extends:
            file: mysql.yml
            service: quanda-mysql
